課題16 system spec作成
tukinasikotonoha/sample_app_for_rspec pull request #3
Opened 2019-10-26 06:08 UTC by yuikotonoha

タスクとユーザーに関するsystem specを下記のテストケースで作成

[正常系]
・ユーザーの新規作成、編集ができること
・ログインが成功すること
・ログインした状態でタスクの新規作成、編集、削除ができること
・マイページにユーザーが新規作成したタスクが表示されること

[異常系]
・メールアドレスが未入力時にユーザーの新規作成、編集が失敗すること
・登録済メールアドレス使用時にユーザーの新規作成、編集が失敗すること
・フォーム未入力時にログインが失敗すること
・ログインしていないユーザーでタスクの新規作成、編集、マイページへの遷移ができないこと
・他のユーザーのユーザー編集、タスク編集ページへの遷移ができないこと

■spec/system/users_spec.rb の実行結果
[![Image from Gyazo](https://i.gyazo.com/18f7200d19fc4903679929d08ee70ec2.gif)](https://gyazo.com/18f7200d19fc4903679929d08ee70ec2)
[![Image from Gyazo](https://i.gyazo.com/aa78681694414ae465d4e1eadf477002.png)](https://gyazo.com/aa78681694414ae465d4e1eadf477002)

■spec/system/user_sessions_spec.rb の実行結果
[![Image from Gyazo](https://i.gyazo.com/473e80ecf27f7e5037121d6f000d3cc7.gif)](https://gyazo.com/473e80ecf27f7e5037121d6f000d3cc7)
[![Image from Gyazo](https://i.gyazo.com/390cdd28a1f206d6b5fa098a8f2738a6.png)](https://gyazo.com/390cdd28a1f206d6b5fa098a8f2738a6)

■spec/system/tasks_spec.rb の実行結果
[![Image from Gyazo](https://i.gyazo.com/965d1330f6cf37219d55ae5e2a3fff7b.gif)](https://gyazo.com/965d1330f6cf37219d55ae5e2a3fff7b)
[![Image from Gyazo](https://i.gyazo.com/68c61d719effccc996a6a2e100da5c98.png)](https://gyazo.com/68c61d719effccc996a6a2e100da5c98)

2019-10-26 08:03 UTC, knt930 reviewed
いくつかコメントしました！

2019-10-26 08:03 UTC, knt930 commented on spec/system/tasks_spec.rb
> +    let(:test_task) { create :task, user_id: 1 }
user_idはuser.idとして指定した方が確実だと思います。

2019-10-26 08:03 UTC, knt930 commented on spec/system/tasks_spec.rb
> +        # タスクの新規作成画面を開く
細かいですが新規ではなく編集画面ではないでしょうか

2019-10-26 08:03 UTC, knt930 commented on spec/system/tasks_spec.rb
> +        Task.create!(title: '課題16', status: 0, user_id: 1)
こちらstatusはenumであれば数値ではなくシンボル名で定義した方がわかりやすいですね。
user_idもuser.idとした方がいいですね！

2019-10-26 08:03 UTC, knt930 commented on spec/system/tasks_spec.rb
> +        Task.create!(title: '課題16', status: 0, user_id: 1)
こちら同上です

2019-10-26 08:03 UTC, knt930 commented on spec/system/tasks_spec.rb
> +    let(:test_task) { create :task, user_id: 2 }
こちらもidを数値で指定するのはよろしくないかと思います。

2019-10-26 08:03 UTC, knt930 commented on spec/system/tasks_spec.rb
> +    let(:kotonoha) { create :user }
複数のdescribeのなかでuserの全く同じ変数の定義をしていますが、一つ上の階層に定義すれば１度で済むはずです！

2019-10-26 08:23 UTC, yuikotonoha commented on spec/system/tasks_spec.rb
> +        # タスクの新規作成画面を開く
すみません、、！
コピペしてコメント変更するの見落としてました。
修正いたします！！

2019-10-26 08:34 UTC, yuikotonoha commented on spec/system/tasks_spec.rb
> +    let(:test_task) { create :task, user_id: 2 }
`let(:test_task) { create :task, user_id: 2 }`
↑この部分、そもそもuser_id がいらないテストでした、、
※テスト通ること確認できたので、`user_id: 2` は削除しますね！

2019-10-26 08:37 UTC, yuikotonoha commented on spec/system/tasks_spec.rb
> +        Task.create!(title: '課題16', status: 0, user_id: 1)
`Task.create!(title: '課題16', status: 0, user_id: 1)`
↑この部分、そもそもuser_id がいらないテストでした、、
※テスト通ること確認できたので、`user_id: 1` は削除しますね！

2019-10-26 08:39 UTC, yuikotonoha commented on spec/system/tasks_spec.rb
> +    let(:kotonoha) { create :user }
```
let(:kotonoha) { create :user }
```
↑DRYにできるんですね・・・！

一つ上の階層に移動して、テスト通ること確認できた為、修正いたします！

2019-10-26 08:45 UTC, yuikotonoha commented on spec/system/tasks_spec.rb
> +        Task.create!(title: '課題16', status: 0, user_id: 1)
シンボル名で定義できるんですね・・！
確かにソッチのほうがわかりやすいです！
修正いたします。

2019-10-26 08:50 UTC, yuikotonoha commented on spec/system/tasks_spec.rb
> +    let(:test_task) { create :task, user_id: 1 }
コメントありがとうございます！
```
let(:test_task) { create :task, user_id: user.id }
```
「user」というletを定義していないのでエラーになってしまいました。


```
let(:test_task) { create :task, user_id: kotonoha.id }
```
↑で修正しますね！

2019-10-26 08:51 UTC, yuikotonoha commented on spec/system/tasks_spec.rb
> +        Task.create!(title: '課題16', status: 0, user_id: 1)
enum もシンボルで指定し直します！

2019-10-26 09:19 UTC, yuikotonoha commented on spec/system/tasks_spec.rb
> +    let(:test_task) { create :task, user_id: 2 }
承知しました！！
（インスタンス).id という指定できるように修正いたします！！

2019-10-26 09:52 UTC, yuikotonoha commented on spec/system/tasks_spec.rb
> +        Task.create!(title: '課題16', status: 0, user_id: 1)
user_idの指定も下記で修正します！
```
Task.create!(title: '課題16', status: :todo, user_id: kotonoha.id)
```

2019-10-27 10:51 UTC, yuji91 commented on spec/factories/users.rb
> +  end
個人的には `user` `other_user` の方がFactoryの意図が分かりやすい気がします🤔

2019-10-27 22:01 UTC, DaichiSaito commented on spec/factories/users.rb
> +  end
余談ですが、こんな風にFakerとか使えばメールアドレスが重複することもないです。
```
factory :user do
    email { Faker::Internet.unique.email }
    password { '12345678' }
    password_confirmation { '12345678' }
  end
```

現状の実装だと一つのexampleの中でこのように書けなくなってしまうので使い勝手が悪いかなーと。
```
let(:user1) = create(:user)
let(:user2) = create(:user)
```

2019-10-27 22:01 UTC, DaichiSaito commented on spec/system/users_spec.rb
> +    context 'マイページへの' do
contextに書くべきことではないと思います。
この場合単純に下のitに「マイページへのアクセスが失敗する」で良いと思います。

2019-10-27 22:01 UTC, DaichiSaito commented on spec/system/users_spec.rb
> +    context '他のユーザーの編集ページへの' do
これも同様。

2019-10-28 02:09 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +        Task.create!(title: '課題16', status: :todo, user_id: kotonoha.id)
`Task.create!` はテストケースの最初に `let!(:user)` で記載した方が読みやすいと思います。

2019-10-28 02:12 UTC, yuji91 commented on spec/system/users_spec.rb
> +        fill_in 'user[email]', with: 'kotonoha@gmail.com'
`kotonoha@gmail.com` など、実在する可能性のあるメールアドレスをテストに使うのは望ましく無いです。

`user@example.com` `admin@example.com` 辺りが無難かと思います。
https://blog.ko31.com/201304/sample-domain-example/

2019-10-28 02:14 UTC, yuji91 commented on spec/system/users_spec.rb
> +        expect(page).to have_content 'Email has already been taken'
フラッシュメッセージだけでなく、ログイン後の挙動や表示が画面上でできないことを1つ確認入れた方がいいです。

2019-10-28 02:15 UTC, yuji91 commented on spec/system/users_spec.rb
> +        expect(page).to have_content "Email can't be blank"
変更前のプロフィール情報を画面上で確認した方が良いですね

2019-10-28 02:16 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +  let(:yukinoha) { create :yukinoha }
ここも `let(:user)` `let(:other_user)` の方がFactoryの意図が伝わると思います。

2019-10-28 02:17 UTC, yuji91 commented on spec/support/task_macros.rb
> +  end
taskの作成は `let!(:task)` で担当させた方が良いですね。
taskを画面上から作成する処理は、Macroではなく正常系のテストケースとして別途記載した方が良いです。

2019-10-28 02:18 UTC, yuji91 commented on spec/support/login_macros.rb
> +    click_button("Login")
細かいですがシングルクォートにしましょう

2019-10-28 02:20 UTC, yuji91 requested changes
`let` を使えるところは積極的に使うことで全体のテストコードの見通しが良くなると思います。

異常系のテストケースではフラッシュメッセージの確認だけでなく、データが更新されていないことを画面上で確認入れた方が良いですね。

2019-10-28 02:28 UTC, yuikotonoha commented on spec/factories/users.rb
> +  end
コメントありがとうございます。
Faker入れるとFactoryで定義するのが１つで済みますね！！便利！
Fakerインストールして、修正いたします！

2019-10-28 02:36 UTC, yuji91 requested changes
```
describe 'ログイン前'
  describe 'サインアップ画面'
    context ''
       it ''
    context ''
       it ''
  describe 'ログイン画面'
  describe 'マイページ画面'

describe 'ログイン後'
  describe 'サインアップ画面'
  describe 'ログイン画面'
  describe 'マイページ画面'
```
の様に、ログイン前と後で最初に `describe` を分けて記載しても良いと思います。

2019-10-28 02:41 UTC, yuikotonoha commented on spec/system/users_spec.rb
> +    context 'マイページへの' do
今の書き方だとitに書くべき内容が 「context と itに分散してしてる」状態ですね。
itに移動させます！

2019-10-28 03:04 UTC, yuikotonoha commented on spec/system/users_spec.rb
> +        fill_in 'user[email]', with: 'kotonoha@gmail.com'
確かに、、誤配信などのリスクも考えられますね。
修正いたします！！

2019-10-28 03:20 UTC, yuji91 commented on spec/system/users_spec.rb
> +        User.create!(email: 'yukinoha@gmail.com', password: 'password', password_confirmation: 'password' )
ここは最上部の `let` を利用して `login(kotonoha)` の時点で Userがcreateされるので、別途 `create!` する必要が無いと思います！

2019-10-28 03:22 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +        Task.create!(title: '課題16', status: :todo, user_id: kotonoha.id)
let(:task_todo) とステータスを指定する letを記載して、それを呼び出す形が良いと思います。

2019-10-28 03:39 UTC, yuikotonoha commented on spec/support/task_macros.rb
> +  end
承知しました！
> 遷移先の画面でデータが確認できることもチェック
↑この部分のテストも作成します！

2019-10-28 04:20 UTC, yuikotonoha commented on spec/system/tasks_spec.rb
> +        Task.create!(title: '課題16', status: :todo, user_id: kotonoha.id)
確かに、
```
Task.create!(title: '課題16', status: :todo, user_id: kotonoha.id)
```
↑今、Acriverecordのメソッドを使って書いてる部分はlet! に修正できますね！

特にステータスを意識しているtaskではないので下記のように修正いたします！
```
let!(:task) { create :task, user_id: user.id }
```

2019-10-28 04:29 UTC, yuikotonoha commented on spec/system/users_spec.rb
> +        expect(page).to have_content 'Email has already been taken'
確かに、、、！
```
# タスク作成画面へアクセスを試みる
visit new_task_path
# タスクの新規作成にアクセスできないことを検証する
expect(page).to have_content 'Login required'
```
↑を追加しますね。

2019-10-28 04:56 UTC, yuikotonoha commented on spec/system/users_spec.rb
> +        expect(page).to have_content "Email can't be blank"
「メールアドレスが変更されていないことを確認する」
↑検証を追加しますね！

2019-10-28 06:51 UTC, yuikotonoha commented on spec/system/users_spec.rb
> +        User.create!(email: 'yukinoha@gmail.com', password: 'password', password_confirmation: 'password' )
確かに、let で定義しているのでcreate! は不要ですね。
削除いたします！！

2019-10-28 08:02 UTC, yuikotonoha commented
ログイン前と後で最初に describe を分けて記載した為、
テストの結果を再度、貼りますね！

■spec/system/users_spec.rb
[![Image from Gyazo](https://i.gyazo.com/ea5d4e77f78936280cd65ed7a4d8c6c0.png)](https://gyazo.com/ea5d4e77f78936280cd65ed7a4d8c6c0)

■spec/system/user_sessions_spec.rb
[![Image from Gyazo](https://i.gyazo.com/1920935466c2f6d7b0245481bdc5bd97.png)](https://gyazo.com/1920935466c2f6d7b0245481bdc5bd97)

■spec/system/tasks_spec.rb
[![Image from Gyazo](https://i.gyazo.com/56cedc9116bd63f91f2a27198ce8d6df.png)](https://gyazo.com/56cedc9116bd63f91f2a27198ce8d6df)

2019-10-28 08:15 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +          task
`let!` でtaskデータを作成しているので、 再度taskを作成する必要は無いと思います。

2019-10-28 08:16 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +  let(:test_task) { create :task, user_id: user.id }
`let(:task)` で良いと思います！
特に理由がなければmodel名をそのまま使って良いかと。

statusを指定したtaskを作りたい場合などは `task_todo` `task_done` など名前を分けて `let` を定義すると良いと思います。

2019-10-28 08:18 UTC, yuji91 commented on spec/system/users_spec.rb
> +          task_create
この部分 `macro` に切り出すべきなのか、直で書いた方が良いのか `let` でDBに作成する対応でも問題ないか等を確認します。

2019-10-28 08:19 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +
余計な空行です

2019-10-28 08:19 UTC, yuji91 commented on spec/system/users_spec.rb
> +
余計な空行です

2019-10-28 08:20 UTC, yuji91 requested changes
コメントしました。

2019-10-28 11:11 UTC, shurijoc reviewed
コメントしたので確認お願いします！

2019-10-28 11:11 UTC, konumashuri commented on spec/system/tasks_spec.rb
> +require 'rails_helper'
.rspec内でrails_helperをrequireしているのでこの記述は不要になります！

2019-10-28 11:11 UTC, konumashuri commented on spec/system/users_spec.rb
> +          task_create
確認したのですが、この場合はfactoryなどでデータを作成するのが良いです。
理由はテスト対象を明確化するためです。 `task_create` macroがあることによって、ブラウザ上の動きも含めてテストしたいという風に読み取れます！

 `it` の中身的に違うと思うので他に意図がない場合はfactoryを使いましょう！

2019-10-28 11:22 UTC, yuikotonoha commented on spec/system/tasks_spec.rb
> +require 'rails_helper'
重複してましたね。。
spec/system/users_spec.rb
spec/system/user_sessions_spec.rb
↑にも書いてたので、併せて削除します！

2019-10-28 11:33 UTC, shurijoc approved these changes
LGTMです！ 🙆‍♂

2019-10-29 01:55 UTC, merged